### ISSUE TITLE
Gebruik HTML alleen voor het opmaken van de content, niet voor styling

### ISSUE THREAD

**Issue by joostf** [ZairaGr/blok-web#5]
Dus geen br en hr elementen gebruik:

https://github.com/ZairaGr/blok-web/blob/master/index%20kopie.html#L72
https://github.com/ZairaGr/blok-web/blob/master/index%20kopie.html#L173

Los dit op in CSS

**Comment by ZairaGr** [comment]
alle hr veranderd naar border-bottom
