### ISSUE TITLE
Gebruik de juiste heading structuur

### ISSUE THREAD

**Issue by joostf** [ZairaGr/blok-web#6]
https://github.com/ZairaGr/blok-web/blob/master/index%20kopie.html#L174

de h4 moet hier een h3 zijn, aangezien de parent section een h2 is

https://github.com/ZairaGr/blok-web/blob/master/index%20kopie.html#L218-L221
een article moet altijd een heading bevatten

**Comment by ZairaGr** [comment]
heading 1, 2, 3 en 4
